version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "daily"
