name: Build and Push

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the Docker image (or version tag)"
        required: true
      release:
        type: boolean
        description: "Is this a full release?"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get docker-slim
        run: |
          SLIM_VERSION=1.40.9

          curl -L -o ds.tar.gz https://downloads.dockerslim.com/releases/$SLIM_VERSION/dist_linux.tar.gz
          tar -xvzf ds.tar.gz
          mv dist_linux/* $GITHUB_WORKSPACE
          rm -rfv ds.tar.gz dist_linux/

      - name: Build starter images
        run: |
          cd $GITHUB_WORKSPACE/docker

          docker build --build-arg="GMOD_BRANCH=live" --tag gluatest_fat_live:latest .
          docker build --build-arg="GMOD_BRANCH=x86-64" --tag gluatest_fat_x86-64:latest .

      - name: Make slim images
        run: |
          cd $GITHUB_WORKSPACE/docker

          BASE=ghcr.io/cfc-servers/gluatest

          $GITHUB_WORKSPACE/docker-slim build \
            --target gluatest_fat_live:latest \
            --http-probe-off \
            --continue-after 30 \
            --show-clogs --show-blogs \
            --tag "$BASE":${{ inputs.tag_name }}

          $GITHUB_WORKSPACE/docker-slim build \
           --target gluatest_fat_x86-64:latest \
           --http-probe-off \
           --continue-after 30 \
           --show-clogs --show-blogs \
           --tag "$BASE"/64bit:${{ inputs.tag_name }}

           if [ "${{ inputs.release }}" = "true" ]; then
            echo "::warning:: Tagging this release as the latest!"
            docker tag "$BASE":${{ inputs.tag_name }} "$BASE":latest
            docker tag "$BASE"/64bit:${{ inputs.tag_name }} "$BASE"/64bit:latest
           fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Tag and push slim images
        run: |
          docker push ghcr.io/cfc-servers/gluatest --all-tags
          docker push ghcr.io/cfc-servers/gluatest/64bit --all-tags
