name: Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1`)

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: $GITHUB_WORKSPACE/project
          file: $/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/cfc-servers/gluatest:latest
            ghcr.io/cfc-servers/gluatest:${{ steps.get_version.outputs.VERSION }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
