name: GLuaFixer

on:
  pull_request:
    paths:
      - 'lua/**'

jobs:
  lint:
    uses: CFC-Servers/github_action_workflows/.github/workflows/lint_glua.yml@feature/shareable
    with:
      config: "https://gist.githubusercontent.com/brandonsturgeon/7b7655e25a33c074a1f33b88d8ce3ac6/raw/c9871f914f5f0562f856eedd3f7814b8639e00b5/glualint.json"
