name: GLuaTest Tester


on:
  workflow_call:
    inputs:
      server-cfg:
        type: string
        required: false
        description: "A path (relative to project directory) with extra server config options"
        default: "gluatest_custom.cfg"

      requirements:
        type: string
        required: false
        description: "A path (relative to project directory) with a list of all requirements to test this project"
        default: "gluatest_requirements.txt"

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-18.04

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          path: project

      - name: "Set up output file"
        run:
          touch "$GITHUB_WORKSPACE"/failures.json
          touch "$GITHUB_WORKSPACE"/project/${{ inputs.server-cfg }}
          touch "$GITHUB_WORKSPACE"/project/${{ inputs.requirements }}

      - name: "Run GLuaTest"
        run:
          docker run \
            --tty \
            --rm \
            --stop-timeout 3 \
            --mount type=bind,source="$GITHUB_WORKSPACE/failures.json",target="/home/steam/gmodserver/garrysmod/data/gluatest_failures.json" \
            --mount type=bind,source="$GITHUB_WORKSPACE/${{ inputs.server-cfg }}",target="/home/steam/gmodserver/custom_server.cfg",readonly \
            --mount type=bind,source="$GITHUB_WORKSPACE/${{ inputs.requirements }}",target="/home/steam/gmodserver/custom_requirements.cfg",readonly \
            ghcr.io/cfc-servers/gluatest

          exitstatus=$?
          if [ $exitstatus -ne 0 ]; then
            echo "::error ::GLuaTest runner didn't exit successfully! Test results are not available."
            exit $exitstatus
          fi

      - name: "Check and report errors"
        run:
          jq -c '.[] | "file=\(.sourceFile),line=\(.lineNumber)::\(.reason)"' "$GITHUB_WORKSPACE/failures.json" | while read i; do
              temp="${i%\"}"
              message="${temp#\"}"
              echo "::error $message"
          done
