name: GLuaTest Tester



on:
  workflow_call:
    inputs:
      server-cfg:
        type: string
        required: false
        description: "A path (relative to project directory) with extra server config options"
        default: "gluatest_custom.cfg"

      requirements:
        type: string
        required: false
        description: "A path (relative to project directory) with a list of all requirements to test this project"
        default: "gluatest_requirements.txt"

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-18.04

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          path: project

      - name: Set up output files
        run: |
          cd $GITHUB_WORKSPACE
          touch $GITHUB_WORKSPACE/failures.json
          touch $GITHUB_WORKSPACE/project/${{ inputs.requirements }}
          echo "gluatest_github_output 1" >> $GITHUB_WORKSPACE/project/${{ inputs.server-cfg }}

      - name: Get latest GLuaTest version
        id: latest-tag-getter
        run: |
          cd $GITHUB_WORKSPACE

          git clone --depth 1 https://github.com/CFC-Servers/GLuaTest.git gluatest
          cd ./gluatest
          cp docker/docker-compose.yml $GITHUB_WORKSPACE/docker-compose.yml

          git fetch --quiet --tags
          latest="$(git tag | tail -1)"
          echo "Latest Tag: $latest"
          echo "::set-output name=LATEST_TAG::$latest"

          cd $GITHUB_WORKSPACE

      - name: "Run GLuaTest"
        env:
          FAILURE_OUTPUT: "${{ github.workspace }}/failures.json"
          REQUIREMENTS: "${{ github.workspace }}/project/${{ inputs.requirements }}"
          CUSTOM_SERVER_CONFIG: "${{ github.workspace }}/project/${{ inputs.server-cfg }}"
          PROJECT_DIR: "${{ github.workspace }}/project"

        run: |
          docker-compose pull
          docker-compose up --no-log-prefix

          exitstatus=$?
          if [ $exitstatus -ne 0 ]; then
            echo "::error ::GLuaTest runner didn't exit successfully! Test results are not available."
            exit $exitstatus
          fi

          echo "Failure output file:"
          cat "$FAILURE_OUTPUT"
          if [ -s "$FAILURE_OUTPUT" ]; then
            echo "::info ::Test failures detected - Failing"
            exit 1
          fi
